 *** CFD Status File Output ***

 CFD 2021 (2021) [20201120]

 Job Name = Scenario 1   Date created: Wed Dec 30 12:13:54 2020



LICENSE STATUS: Cloud id is empty using ADLM
Check Out motion License:    Successful
LICENSE STATUS: License checked out successfully...
Open results restart file: Scenario 1.res.s6

Restart results file: Scenario 1.res.s6
Res file compatible with CFdesign version: 21.0-20201120
Creation date and time: Wed Dec 30 12:13:19 2020 
Analysis title: CFD Default control file settings
Processing input ...

 Reading CFdesign model file

Processing mesh input ...

Restart geometry file: Scenario 1.gm
Geometry file created by CFD version: 21.0-20201120
Creation date and time: Wed Dec 30 12:13:18 2020 
Model size: 2201 Nodes  7241 Elements
            0 Fluid Nodes  0 Fluid Elements
            2201 Solid Nodes  7241 Solid Elements

Loading restart mesh input
Mesh input complete
Processing results input ...
Open results restart file: Scenario 1.res.s6

Restart results file: Scenario 1.res.s6
Res file compatible with CFdesign version: 21.0-20201120
Creation date and time: Wed Dec 30 12:13:19 2020 
Analysis title: CFD Default control file settings
Results input complete
Processing BC input ...
Loading restart BC data ...
BC restart input complete
Analysis Initialization Complete
Input processing complete
** FINITE ELEMENT SUMMARY FOLLOWS...
2201 Total Nodes    0 Fluid Nodes      2201 Solid Nodes
7241 Total Elems     0 Fluid Elems      7241 Solid Elems
1 Inlets    0 Outlets    0 Unknowns
 Analysis started

 ###  WARNING: cfd_analyzec.cpp 843 
 # *** FLOW = OFF - no fluid nodes 
 ############################################## 
 *** Analysis Information 
 Steady State is ON






 Flat lines detected in Convergence Monitor - Auto Stop.
Save results restart file: Scenario 1.res.s9
Begin Post-Processing Calculations ...

 Performing output calculations (stream function, vorticity,..)

 Outputting turbulent wall data
Post-Processing Calculations Done
Begin Post-Processing File Output ...

 Outputting CFDisplay results - Type 1 data
Post-Processing File Output Done
New boundary condition file: Scenario 1.bc
Open results restart file: Scenario 1.res.s3

Restart results file: Scenario 1.res.s3
Res file compatible with CFdesign version: 21.0-20201120
Creation date and time: Wed Dec 30 12:08:14 2020 
Analysis title: CFD Default control file settings
Open results restart file: Scenario 1.res.s6

Restart results file: Scenario 1.res.s6
Res file compatible with CFdesign version: 21.0-20201120
Creation date and time: Wed Dec 30 12:13:19 2020 
Analysis title: CFD Default control file settings
Open results restart file: Scenario 1.res.s9

Restart results file: Scenario 1.res.s9
Res file compatible with CFdesign version: 21.0-20201120
Creation date and time: Wed Dec 30 12:13:56 2020 
Analysis title: CFD Default control file settings
 *** 1 non-fatal warnings occurred, review status file ***


CFDESIGN FLAGS                           Value


 
